services:
  streamrs:
    build: ./streamrs
    ports:
      - "5000:8080"
        #- "12345:12345/udp"
    depends_on:
      proxy:
        condition: service_started

  proxy:
    image: nginx
    ports:
      - "12345:12345/udp"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
